sudo: false
language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r requirements-testing.txt
script:
    PYTHONPATH=$PWD:$PYTHONPATH pytest --cov web
after_success:
    coveralls
